# Generated by Django 6.1.1 on 2026-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(db_index=True, max_length=128)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=6, max_digits=10)),
                ('price_sample_count', models.PositiveIntegerField(default=1, help_text='Number of CSV rows averaged into retail_price for this station.')),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('geocode_source', models.CharField(blank=True, choices=[('census_place', 'Census Gazetteer (place)'), ('census_cousub', 'Census Gazetteer (county subdivision)'), ('nominatim', 'Nominatim'), ('manual', 'Manual override')], max_length=32)),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'fuel station',
                'verbose_name_plural': 'fuel stations',
                'ordering': ('state', 'city', 'truckstop_name'),
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='fuelstation_lat_lon_idx'), models.Index(fields=['state', 'city'], name='fuelstation_state_city_idx'), models.Index(fields=['retail_price'], name='fuelstation_price_idx')],
            },
        ),
    ]
